---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-forward-auth
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: traefik-forward-auth
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: traefik
      namespace: networking
  values:
    authHost: "auth.${SECRET_DOMAIN}"
    cookie:
      domain: "${SECRET_DOMAIN}"
    middleware:
      enabled: true
    providers:
      google:
        enabled: true
        clientId: "${SECRET_GOOGLE_CLIENT_ID}"
        clientSecret: "${SECRET_GOOGLE_CLIENT_SECRET}"
    restrictions:
      whitelist: "${SECRET_TFA_WHITELIST}"
    env:
      TZ: America/Toronto
    ingress:  
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "auth.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "auth.${SECRET_DOMAIN}"
            secretName: "traefik-forward-auth-tls"
