apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  channel: server-alerts
  username: Flux
  secretRef:
    name: discord-webhook

---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: discord
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
    - kind: Kustomization
      name: "*"
  exclusionList:
    - "error.*lookup github\\.com"
    - "waiting.*socket"
    - "CustomResourceDefinition/(bgppeers|addresspools)\\.metallb\\.io configured"
