apiVersion: v1
data:
    address: ENC[AES256_GCM,data:ZoeYDbLdYAbT1LJW7mi3HEZTy+/HMWExctWibA5/m+5Ymw7m/mhqGiQ4IATW8ya19xHwIf0jA6Gq+Pp0d4+3f8QXvuJhZgTSbwYBpo+TbhtYBvi9oNo6tyVbKXU1xqEC4z2v+BpjvoNSZUhiFezLMeODQEBgOTbOP3pGQhLkBNSM72T17rIRDlPGwhm7xsuIPhHqdrnqI1CDfefVSJ+/fA==,iv:0zc1x6mkgL92EcYsSmUoCHwNsAMPcXzD8n/jtqXBdO8=,tag:vXO6Du9CWxKxTGwNsPXhQQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: discord-webhook
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-20T03:08:46Z"
    mac: ENC[AES256_GCM,data:yU7mOrraGA8XZSCQHcKbwyDr1UIEIGNEOOGD07akaB5fPQFhRWZy3g7l0zoT1qNftyi4biaSLD8OQ+sf+SfQJeWCUTu/+6B4kl9MV6l1bX+8GZdolf5aYmGc2Oauwmms07/9ht2wsiLNuYBfvwBWr9G4SCevDB83RJqo0OmzBOM=,iv:MLRdpF96UlzotHIEv1Nl8Kb/BMVionCfxjvZngsFq1Y=,tag:Kfqj+CWhic1i7WZ5+IWJew==,type:str]
    pgp:
        - created_at: "2021-09-20T03:08:45Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6u12LwpdXWWARAAm100UAHfdTsuziiiQiTjBzuOXRISHW2ryGmGtvluCTV2
            2zJuO2f8AbKQHD54Fw5LCiWXHpUfZEqPgo2oOTA+kvbISgEJZa/VJNER2dv5fNtU
            M5zCkkFAMsa9TPFXCZNB/toTz+rij4lYdqaHDmnwjXshYgvvRyX0+0zsU8NkQJuR
            V2jn3faKvdDGNdJw+ODXVwU4v5IVeS66ud/MRIfOq1WHGivGHI+w0h+N/yTqsBoY
            bpe+WfyQFRNBj73p+3T15CSxZDu2waCurt4CkXN9y25k8qSctf0tIjLhxTFTOj00
            lrQKIrFa4Hy2ISTqEVCOy/454+Dd9HaP9nZIFfe+PdjA6JPrHjI6ebLvCcMl5jTC
            WZmUNqING/tV2qBzv59+faoTYnjmMGguH+ZRNv61mVbqXCjnwi+OalqFTQimFcR9
            DOMfXYKx9lnh7byrQw6GKFV1rwlZ4kEbd9Y3i5bH48Ev3HnY8IuhGekTXqQD9Yyg
            ig4bEaDuDdWRasPXuLADCqL//eiNJ/LTpgoTnQCZUoiTRK3mDL7/qxiywTtSeAMr
            BsuFEVH3g7WUJ1kxAQvtC5RVvej1bRy+U5ggMwMyu/JV5Pf0W4VR9cW12oy56GR8
            l5Ev6Dgd3a4ASzAVCJWvlgV9FMRaMjg5PPn2/esyXUO+pmBbNGe2fgJnzKKlM3zU
            aAEJAhWoYdo3NoY/XMC+mBPCOMW3/NCnJSTdxV4hKUx073+Lm2K1ppdwLwsMHZBW
            HJ+dM5MYTWo5LB2EZwTpKWVSFyUJGgvGZs8eQZzh1MYUxUM+w7dByVmhvHSshkt1
            l7EnU1ogV+0B
            =xrwF
            -----END PGP MESSAGE-----
          fp: 3F6B2A9616F3BEE2B6AB910C89D96C16BE957D07
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
