apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-config-v1
  namespace: home
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-db-v1
  namespace: home
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi
