---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-forge-v1
  namespace: games
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block
