---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-forge
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    imageTag: java8
    minecraftServer:
      eula: "TRUE"
      type: "FORGE"
      version: "1.16.5"
      ops: "phybros"
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.86.241
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-forge-v1
