---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-potato-smp
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 0
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 6Gi
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      version: "1.19.2"
      pvp: "true"
      gameMode: survival
      vanillaTweaksShareCodes: ["MaEdu5", "0PQfIm", "x0CZVp", "Zu07nn"]
      levelSeed: "iamacamel"
      overrideServerProperties: true
      whitelist: "phybros,gimgam5000"
      viewDistance: 10
      spawnProtection: "0"
      icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png"
      difficulty: "hard"
      motd: "\u00a7apotatoes\u00a7d are \u00a79op\u00a7d"
      memory: 5120M
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_POTATO_SMP_ADDR}"
      rcon:
        enabled: true
        port: 25575
        password: "${SECRET_MC_RCON_PASSWORD}"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-potato-smp-v1
