---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-potato-smp
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 5Gi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      version: "1.19.2"
      pvp: "true"
      gameMode: survival
      vanillaTweaksShareCodes: ["V4YEgn"]
      levelSeed: "iamacamel"
      overrideServerProperties: true
      whitelist: "phybros,gimgam5000"
      viewDistance: 10
      spawnProtection: "0"
      icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png"
      difficulty: "hard"
      motd: "\u00a7apotatoes\u00a7d are \u00a79op\u00a7d"
      ops: "phybros,gimgam5000"
      memory: 4096M
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_POTATO_SMP_ADDR}"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-potato-smp-v1
