---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: samba
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: EST5EDT
    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            auth:
              - user: scans
                group: scans
                uid: 568
                gid: 568
                password: scans
            global:
              - "force user = scans"
              - "force group = scans"
              - "create mask = 0644"
              - "directory mask = 0755"
            share:
              - name: Scans
                path: /share1
                browsable: yes
                readonly: no
                guestok: no
                comment: "Printer scans"
                veto: yes

    podSecurityContext:
      supplementalGroups:
        - 568

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_SAMBA_ADDR}"
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139

    persistence:
      share1:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/mergerfs/storage/scans"

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
