---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: samba
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: samba
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      # -- Set the container timezone
      TZ: EST5EDT

    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            auth:
              - user: scansuser
                group: scansgroup
                uid: 100
                gid: 101
            global:
              - "force user = scansuser"
              - "force group = scansgroup"
            share:
              - name: Scans
                path: /share1
                browsable: yes
                readonly: no
                guestok: yes
                comment: "Printer scans"
                veto: no

    podSecurityContext:
      supplementalGroups:
        - 568

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_SAMBA_ADDR}"
        ports:
          tcp:
            enabled: true
            protocol: TCP
            port: 445
          netbios:
            enabled: true
            protocol: TCP
            port: 139

    persistence:
      share1:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: "/mergerfs/storage/scans"

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
