---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-config-v1
  namespace: default
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-db-v1
  namespace: default
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
