---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tika
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.7.0-minimal

    service:
      main:
        ports:
          http:
            port: 9998
