---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: pod-arcade-desktop
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    defaultPodOptions:
      securityContext:
        supplementalGroups:
          - 3000

    controllers:
      main:
        type: statefulset
        containers:
          main:
            env:
              MQTT_HOST: ws://pa-server-server/mqtt
              DESKTOP_ID: pa-retroarch
              DESKTOP_PSK: magicPa$$wordForDesktops
              
              WLR_BACKENDS: headless
              DRI_DEVICE_MODE: MKNOD
              UINPUT_DEVICE_MODE: NONE
              DISABLE_HW_ACCEL: "false"
              WLR_RENDERER: gles2
              WLR_NO_HARDWARE_CURSORS: "1"
              FFMPEG_HARDWARE: "1"
              XDG_RUNTIME_DIR: /tmp/sway
              PULSE_SERVER: unix:/tmp/pulse/pulse-socket
              DISPLAY: :0

            image:
              repository: ghcr.io/pod-arcade/desktop
              tag: main
          sidecar:
            env:
              PUID: "1000"
              PGID: "1000"
              UNAME: ubuntu
            image:
              repository:  gameonwhales/retroarch
              tag: edge

    service:
      main:
        ports:
          http:
            port: 80
          https:
            port: 8443
          mqtt:
            port: 1883

    persistence:

      retro:
        enabled: true
        existingClaim: pod-arcade-v1
        globalMounts:
          - path: /home/ubuntu/.config/retroarch
