---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.86.210-192.168.86.253
  SVC_TRAEFIK_ADDR: 192.168.86.210
  NAS_ADDR: 192.168.86.200
  SVC_PLEX_ADDR: 192.168.86.211
  SVC_SAMBA_ADDR: 192.168.86.222
