---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-potato-creative
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 0
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 4Gi
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      version: "1.19.2"
      vanillaTweaksShareCodes: ["MaEdu5", "0PQfIm", "x0CZVp", "Zu07nn"]
      pvp: "true"
      gameMode: creative
      levelSeed: "iamacamel"
      overrideServerProperties: true
      whitelist: "phybros,gimgam5000"
      viewDistance: 10
      spawnProtection: "0"
      icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/a/aa/Golden_Carrot_JE4_BE2.png"
      difficulty: "hard"
      motd: "\u00a7agolden carrots\u00a7d are \u00a79op\u00a7d"
      ops: "phybros,gimgam5000"
      memory: 3072M
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_POTATO_CREATIVE_ADDR}"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-potato-creative-v1
