# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_LETSENCRYPT_EMAIL: ${BOOTSTRAP_LETSENCRYPT_EMAIL}
  SECRET_DOMAIN: ${BOOTSTRAP_DOMAIN}
  SECRET_ROUTE53_REGION: ${BOOTSTRAP_ROUTE53_REGION}
  SECRET_ROUTE53_ACCESS_KEY: ${BOOTSTRAP_ROUTE53_ACCESS_KEY}
  SECRET_ROUTE53_ZONE_ID: ${BOOTSTRAP_ROUTE53_ZONE_ID}
