---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mc-22
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 0
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 5Gi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      version: "1.18.2"
      pvp: "true"
      gameMode: survival
      levelSeed: "-1947113420"
      overrideServerProperties: true
      whitelist: "phybros,gimgam5000"
      viewDistance: 10
      spawnProtection: "0"
      difficulty: "hard"
      motd: "\u00a76\u00a7lBasement\u00a7c\u00a7l Dwellers\u00a7e\u00a7l United\u00a7d (\u00a7abirds\u00a7d are \u00a79pog\u00a7d)"
      ops: "phybros"
      memory: 4096M
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_22_ADDR}"
      extraPorts:
        - name: servertap
          containerPort: 4567
          protocol: TCP
          service:
            enabled: true
            embedded: false
            port: 4567
            type: LoadBalancer
            loadBalancerIP: "${SVC_MC_22_ST_ADDR}"
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            port: 8123
          ingress:
            enabled: true
            ingressClassName: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-production"
              traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
              traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-forward-auth@kubernetescrd"
            hosts:
              - host: "mc.${SECRET_DOMAIN}"
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                  - "mc.${SECRET_DOMAIN}"
                secretName: "mc-tls"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-22-v1
