---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: homepage-contents
    namespace: default
    files:
      - homepage.html
generatorOptions:
  disableNameSuffixHash: true
