---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mc-school
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 6Gi
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      version: "1.20.4"
      pvp: "default"
      gameMode: survival
      overrideServerProperties: true
      viewDistance: 10
      spawnProtection: 4
      enableCommandBlock: true
      icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/Potato_JE3_BE2.png"
      difficulty: "hard"
      motd: "\u00a7f\u00a7l-SCHOOL SMP-\u00a72 birds are cool"
      memory: 5120M
      serviceType: LoadBalancer
      ops: "phybros,gimgam5000"
      loadBalancerIP: "${SVC_MC_SADDR}"
      extraPorts:
        - name: servertap
          containerPort: 4567
          protocol: TCP
          service:
            enabled: true
            embedded: false
            port: 4567
            type: LoadBalancer
            loadBalancerIP: "${SVC_MC_22_ST_ADDR}"
          ingress:
            enabled: false
      rcon:
        enabled: true
        port: 25575
        password: "${SECRET_MC_RCON_PASSWORD}"
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-school-v1
