---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mc-survival
  namespace: games
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1000m
    minecraftServer:
      eula: "TRUE"
      type: "PAPER"
      pvp: "false"
      gameMode: survival
      motd: "Gaming Dungeon Survival Server"
      ops: "phybros"
      memory: 2048M
      serviceType: LoadBalancer
      loadBalancerIP: "${SVC_MC_ADDR}"
    podAnnotations:
      backup.velero.io/backup-volumes: datadir
    persistence:
      dataDir:
        enabled: true
        existingClaim: mc-survival-v1
