---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            region: ${SECRET_ROUTE53_REGION}
            accessKeyID: ${SECRET_ROUTE53_ACCESS_KEY}
            hostedZoneID: ${SECRET_ROUTE53_ZONE_ID}
            secretAccessKeySecretRef:
              name: route53-secret
              key: secret-access-key
