apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-v1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi
