---
apiVersion: v1
kind: Secret
metadata:
   name: restic-sonarr
   namespace: default
type: Opaque
stringData:
   RESTIC_REPOSITORY: "${SECRET_RESTIC_REPO}/sonarr"
   RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
   AWS_ACCESS_KEY_ID: ${SECRET_RESTIC_AWS_ACCESS_KEY_ID}
   AWS_SECRET_ACCESS_KEY: ${SECRET_RESTIC_AWS_SECRET_ACCESS_KEY}

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
   name: sonarr
   namespace: default
spec:
   sourcePVC: sonarr-config-v1
   trigger:
      schedule: "35 07 * * *"
   restic:
     pruneIntervalDays: 15
     repository: restic-sonarr
     cacheStorageClassName: local-path
     retain:
       hourly: 1
       daily: 1
       weekly: 1
       monthly: 1
       yearly: 1
     copyMethod: Snapshot
