---
apiVersion: v1
kind: Secret
metadata:
   name: aws-creds
   namespace: db
type: Opaque
stringData:
   ACCESS_KEY_ID: ${SECRET_RESTIC_AWS_ACCESS_KEY_ID}
   ACCESS_SECRET_KEY: ${SECRET_RESTIC_AWS_SECRET_ACCESS_KEY}
