---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nocodb
  namespace: db
spec:
  instances: 2
  bootstrap:
    initdb:
      database: nocodb
      owner: nocodb
  storage:
    storageClass: rook-ceph-block
    size: 1Gi
  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      destinationPath: "s3://24mc-cnpg-backups/nocodb"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY

# # test, remove later
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: backup-example
#   namespace: db
# spec:
#   cluster:
#     name: nocodb
