---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nocodb
  namespace: db
spec:
  instances: 2
  bootstrap:
    initdb:
      database: nocodb
      owner: nocodb
  storage:
    storageClass: local-path
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: "2w"
    barmanObjectStore:
      destinationPath: "s3://24mc-cnpg-backups"
      wal:
        compression: gzip
        maxParallel: 8
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY

# # test, remove later
# ---
# apiVersion: postgresql.cnpg.io/v1
# kind: Backup
# metadata:
#   name: nocodb
#   namespace: db
# spec:
#   cluster:
#     name: nocodb
