apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v1
  namespace: default
  annotations:
    benji-backup.me/fsfreeze: "yes"
  labels:
    backup-this-pvc: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 4Gi
