---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-config-v1
  namespace: default
  annotations:
    benji-backup.me/fsfreeze: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 64Mi
